export default {
  SET_TOKEN_DATA: 'SET_TOKEN_DATA',
  SET_TOKEN_META: 'SET_TOKEN_META',
  SET_TOKEN_UPGRADE_PARAMETERS: 'SET_TOKEN_UPGRADE_PARAMETERS',
  SET_TOKEN_UPGRADE_SIGNATURE: 'SET_TOKEN_UPGRADE_SIGNATURE',
  SET_TOKEN_UPGRADE_TRANSACTION_HASH: 'SET_TOKEN_UPGRADE_TRANSACTION_HASH',
  SET_ADDRESS_DATA: 'SET_ADDRESS_DATA',
  PAGINATION_SET_PAGE_NUMBER: 'PAGINATION_SET_PAGE_NUMBER',
  PAGINATION_INITIALIZE_PAGINATOR: 'PAGINATION_INITIALIZE_PAGINATOR',
  SET_WEB3_OPTIONS: 'SET_WEB3_OPTIONS',
  SET_WEB3_SELECTION: 'SET_WEB3_SELECTION',
  SET_WEB3: 'SET_WEB3',
  SET_WEB3_ETH_ACCOUNTS: 'SET_WEB3_ETH_ACCOUNTS',
}
