export default {
  SET_TOKEN_DATA: 'SET_TOKEN_DATA',
  SET_TOKEN_META: 'SET_TOKEN_META',
  SET_ADDRESS_DATA: 'SET_ADDRESS_DATA',
  PAGINATION_SET_PAGE_NUMBER: 'PAGINATION_SET_PAGE_NUMBER',
  PAGINATION_INITIALIZE_PAGINATOR: 'PAGINATION_INITIALIZE_PAGINATOR',
  SET_WEB3_OPTIONS: 'SET_WEB3_OPTIONS',
  SET_WEB3_SELECTION: 'SET_WEB3_SELECTION',
  SET_WEB3: 'SET_WEB3',
}
