export default {
  SET_TOKEN_DATA: 'SET_TOKEN_DATA',
  SET_TOKEN_META: 'SET_TOKEN_META',
  PAGINATION_SET_PAGE_NUMBER: 'PAGINATION_SET_PAGE_NUMBER',
  PAGINATION_INCREASE_PAGE_NUMBER: 'PAGINATION_INCREASE_PAGE_NUMBER',
  PAGINATION_DECREASE_PAGE_NUMBER: 'PAGINATION_DECREASE_PAGE_NUMBER',
  PAGINATION_SET_ITEM_COUNT: 'PAGINATION_SET_ITEM_COUNT',
  SET_WEB3_OPTIONS: 'SET_WEB3_OPTIONS',
  SET_WEB3_SELECTION: 'SET_WEB3_SELECTION',
  SET_WEB3: 'SET_WEB3',
}
